### ISSUE TITLE
ASP.NET Core Web API + Kestrel + IIS response time is slow

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#87]
_From @qazq on April 6, 2017 4:40_

I publish my Web API application to IIS server 8.5 (running on Windows Server 2012), but the performance is not good. If I run Web API by `dotnet myapi.dll` (pure Kestrel Http Server), the performance is good.

**Client to IIS**
![client-to-iis](https://cloud.githubusercontent.com/assets/997727/24737819/3bb2ab3a-1ac4-11e7-993f-b1e29e8a9a12.PNG)

**Client to Kestrel**
![client-to-kestrel](https://cloud.githubusercontent.com/assets/997727/24738014/57862322-1ac5-11e7-9bbe-b77f875112fc.PNG)

**localhost to IIS**
![localhost-to-iis](https://cloud.githubusercontent.com/assets/997727/24738034/7ddc9c36-1ac5-11e7-97cd-dded5df43e50.PNG)

**localhost to Kestrel**
![localhost-to-kestrel](https://cloud.githubusercontent.com/assets/997727/24738039/88be7da4-1ac5-11e7-9202-4847163fb650.PNG)

Content download time is slow if the web API run on the IIS. If connect from the localhost looks like work normal.

Is it possible to tune the performance? Or this is IIS limitation?

_Copied from original issue: aspnet/IISIntegration#351_

**Comment by Tratcher** [comment]
@mikeharder

**Comment by PonchoPowers** [comment]
If you create a VM, install Windows Server 2012 on it, and then create a new ASP.NET Core Web Application (.NET Core) project in Visual Studio, using the Web API template, and then publish it to a directory and set up IIS to serve the default website from that directory, the response times for me are around 70ms in both IIS and Kestrel. @qazq is the AspNetCoreModule the first module in the list?

**Comment by qazq** [comment]
I create a new ASP.NET Core Web Application project in Visual Studio, using the default Web API template, and then publish it to my server (Windows Server 2012)

Open the URL 'http://192.168.1.50/api/values' by Chrome, and the response times are 202ms (Content Downlaod time is 196ms)
![iis_test_default_api_project](https://cloud.githubusercontent.com/assets/997727/24842385/c11cfce6-1dc9-11e7-8ed5-c2d65353d011.PNG)

I stop my IIS service and run `dotnet myapi.dll`, the response times are around 30ms
![iis_test_default_api_project_no_iis](https://cloud.githubusercontent.com/assets/997727/24842418/133f48ee-1dca-11e7-806c-85df1215a236.PNG)

My web.config is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->

  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
```

**Comment by qazq** [comment]
I remove all the modules from IIS configuration, just keep `AspNetCoreModule` (the first module in the list) and `AnonymousAuthenticationModule`. The response times are still slow.

**Comment by shirhatti** [comment]
@qazq Are you measuring cold-startup time? Or are these warm request times?

**Comment by qazq** [comment]
@shirhatti These are warm request times.

**Comment by mateanticevic** [comment]
I have the same problem and noticed something strange. There's a huge amount of TCP packets as they are way below the MTU size limit. I reckon this is the cause of the slow download. This happens only with IIS in front of Kestrel. With Kestrel alone it doesn't happen.

**AspNetCore MVC 1.1.1** ~675kB ~11500 packets ~2s download

![wireshark_tcp_small](https://cloud.githubusercontent.com/assets/7413632/25617874/b0aa986e-2f44-11e7-93c9-49996e7d2915.PNG)

Tested a similar call in an old app with Web forms and the difference is obvious.

**Web forms** ~675kB ~750 packets ~200ms download

![tcp_full](https://cloud.githubusercontent.com/assets/7413632/25617875/b221d3d8-2f44-11e7-9fb1-7b7de84b4c59.PNG)

**Comment by DotNetPart** [comment]
Is there any update on this?

**Comment by ubiqs** [comment]
I also observed the same issue. Running same app via visual studio is much faster then when deployed in IIS. Is there any solution to this ?

**Comment by Antevirus** [comment]
I have the same issue with IIS 8.5 infront of Kestrel. But fast without. 

Hows it going with this issue?

**Comment by ubiqs** [comment]
Hi,

Actually I had two issues.
1. Angular rendering for loop, and inside the loop some 3rd party
controls., which was the major bottle neck.
2. I used to feel slow speed on IIS, compared to local Visual Studio,.

But when 1st issue was resolved, the 2nd one did not feel important and had
satisfactory response.

So I did not investigate the second one.

See if there is any other bottleneck.

thanks
ameet

**Comment by muratg** [comment]
@mateanticevic Were you able to do any more  investigation on this? Any leads?

**Comment by mateanticevic** [comment]
@muratg 
No. But I can confirm the issue still exists with AspNetCore 2.0.1.

**Comment by heffay** [comment]
Also experiencing this slowness when Web API is hosted behind IIS. It seems to be adding ~225-250ms latency pretty consistently. This is in contrast to directly hosting with kestrel

**Comment by mchenx** [comment]
I encountered a similar issue but a little bit different
I created an asp.net core 2.0 mvc web app, by using the template, just the sample the template generates, nothing modified. Run a few tests by using ab (Apache Bench) , sending GET requests with url  
http://{server:port}/home

If using iis express ( launched by visual studio), I got around 25 requests/sec peformance.
If using dotnet run, I got around 2,000 requests/sec, yes, two thousands, 80x faster than iis express.
After deployed to azure web app, I run the ap and got around 5 requests/sec.

Sounds similar?

this is when using IIS express
![image](https://user-images.githubusercontent.com/1550186/35617687-dcbf0042-06b3-11e8-90a7-f50add26d9a1.png)


this is when using kestrel directly ( via 'dotnet run' or 'dotnet myproj.dl')
![image](https://user-images.githubusercontent.com/1550186/35617704-e42cfb86-06b3-11e8-811f-5af30331906a.png)

**Comment by ubiqs** [comment]
There is certainly some overhead between the Kestrel server and IIS.
We are still using 1.x and not upgraded to 2.x.

Although on our production we are not facing any performance issues as such.

Although I realized is that new experimentation is good with new platforms,
but for anything to do with Production Deployed applications,
stick to those technologies that work. And wait for newer to get mature and
stable :)

**Comment by mchenx** [comment]
I deployed the web app on IIS10 and there seems to be no issues, the performance is good enough for me, around 1300 requests/sec.

![image](https://user-images.githubusercontent.com/1550186/35660312-458db2e8-0746-11e8-9fad-2a7e8fd32a4c.png)

I'll leave the iis express as it is just for dev

**Comment by JTOne123** [comment]
I can confirm the issue still exists with latest AspNetCore 2 and IIS8

**Comment by hscanlan** [comment]
I'm also having this issue.

**Comment by Disturbing** [comment]
Same issue.

**Comment by FrancoisAR** [comment]
Same issue here. ASP core 201, IIS8 on win2012-

**Comment by shirhatti** [comment]
This issue has turned into a catch-all issue for ANCM performance issues. Unfortunately, most folks who have commented haven't provided sufficient information for us to investigate. I apologize in advance if I've closed this bug and you have an unresolved issue. Please feel free to create a new bug with more information.

I have created a [new bug](https://github.com/aspnet/IISIntegration/issues/587) to track the TCP packet too small issue.

Yes, we are aware that running Kestrel behind ANCM is slower than running Kestrel standalone but most of that can be attributed to just the realities of running behind a proxy. That being said we are eager to continue to find performance bottlenecks in ANCM and fix them.

**Comment by jds80021** [comment]
From the latest comments, It sounds like this isn't resolved. I am also experiencing this issue with a very basic dotnet core 2.01 webapi.  Why did this get closed?

**Comment by mikeharder** [comment]
@jds80021: Please open a new issue and describe the specific performance problem you are seeing (throughput or latency).  It also helps if you can provide sample code so we can reproduce the behavior.

**Comment by jkotalik** [comment]
@jds80021 if you could open the issue in IISIntegration, it would be preferred.

**Comment by winfredchen** [comment]
I am experiencing this issue. 
Local (Win10) VS(2017) debug: ok
Local IIS : ok 
Server (Server 2016): dotnet run with code: ok
Server (Server 2016): publish - very slow, even the default /api/Values action take 10 seconds. ( I have tried publish debug/release mode; host in iis and use cmd: dotnet xxx.api.dll )

**Comment by cdavernas** [comment]
I dont know if your issues are related to that, but I found that some logging settings can and will absolutely screw with app performances. I just faced that issue by having multiple appsettings files, with my production one not setting the logging "System" filter to "None". Setting it back to "None" improved performances by 25x

**Comment by KamelJabber** [comment]
I couldn't tell you if I have the exact same scenario here, however, if it helps anyone.

I was getting very bad performance running in a Windows Server 2008.

I moved to Windows Server 2012 and it started flying!

I got the idea from someone above or a different thread, either way, it's very fast under 2012

**Comment by skashif** [comment]
I am facing a similar issue where the content-download time is degrading the performance. My issue is that when I access the sites on one of the VMs (irrespective of whether I am running it on the deployed server(VM) or not) I am getting the API response performance as below,

![image](https://user-images.githubusercontent.com/23385818/48412416-92c90f80-e76a-11e8-989c-1efe5687ef0c.png)

On another note, if I am accessing the website from my development machine which is not one of the VMs but a local desktop, I get the following response time,
![image](https://user-images.githubusercontent.com/23385818/48413437-c35e7880-e76d-11e8-9b5c-0d5015ded82d.png)


Before I explain further, I would like to throw light on the application tech stack and versions -
**API solution**
.Net Core 2.1.4 
**Client**
Angular 6
**Host environment**
Windows 2012 R2
IIS 8.5.*

So as you can see with hosting environment I have gone IIS + Krestel route but I have also tried hosting the API solution as a standalone using HTTPsys(formerly know as Weblistener) but the results were no different but even worse.

What am I trying to do?
My API returns a large JSON which has around 18K+ rows with Response compression (gzip) I have got down the response size to 1.9MB. 

It would be great if someone could help me out here also,
1) Open to try a better approach to handle a large dataset?
2) Using different deployment techniques if that helps my cause?
3) Apply addition (IIS/Krestel) configs before deployment to make the API respond better?

This is a dealbreaker for me as you can notice I am making this data available in few ms so the response time is imperative for me.

**Comment by jkotalik** [comment]
Few things to try:

- This sounds like an application issue (as two servers both showed the same issue), but what performance do you see using Kestrel standalone? If the performance is bad there, then it's most likely an application error as we see json responses with significantly lower latency.
- How are you writing the response? If you are accessing a database to get json data, be careful with how you are querying.
- Is the json response static content? If so, you can use the static file middleware https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.1
- Try debug stepping through your code on your local machine or enable logging with timestamps https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1. This can give you a better perspective on how long the request lifetime is in Kestrel.

**Comment by skashif** [comment]
@jkotalik - Thank you for your reply on my issue. Below are the replies with respect to the pointers in your comment,

- I will share the result of Kestrel standalone performance in the next comment
- Under the hood my API is fetching a response from a Redis Server which returns a JSON serialized array of strongly typed object, so I am returning JSON(18K+ rows). Also, we do not have to worry about DB Access here as it is not part of this request.
- JSON response is not a static content as mentioned above.
- Sharing logger details as requested
+ API request log in case of request made from localhost(on of the VMs)
![image](https://user-images.githubusercontent.com/23385818/48470935-c9f5fa00-e818-11e8-8dd7-1e75249cb04d.png)

Corresponding network timing,
![image](https://user-images.githubusercontent.com/23385818/48470791-67046300-e818-11e8-8cf2-d91051049e79.png)

+ API request log in case of request made from my local machine
![image](https://user-images.githubusercontent.com/23385818/48471118-2b1dcd80-e819-11e8-8f34-b095c68ebb56.png)

Corresponding network timing,
![image](https://user-images.githubusercontent.com/23385818/48471167-44267e80-e819-11e8-9fca-9091a9c5dbc1.png)


I have highlighted the time difference I have observed in the log for both the calls. I appreciate you showing interest in helping me out and also if you need any additional information then please let me know. Thanks.

**Comment by jkotalik** [comment]
@skashif did you manage to get the performance of standalone Kestrel?
